import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#5C8587",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  box: {
    backgroundColor: "#4A90E2",
    paddingVertical: 20,
    paddingHorizontal: 30,
    borderRadius: 16,
    marginBottom: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: "#fff",
    textAlign: "center",
  },
  foto: {
    width: 200,
    height: 200,
    borderRadius: 12,
    marginTop: 10,
    borderWidth: 3,
    borderColor: "#4A90E2",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 4,
  },
  inputContainer: {
    marginTop: 12,
    width: "100%",
    gap: 8,
  },
  inputLabel: {
    fontWeight: "600",
    marginBottom: 4,
    color: "#fff",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
    marginBottom: 8,
  },
  listContainer: {
    marginTop: 20,
    width: "100%",
  },
  listTitle: {
    fontWeight: "700",
    marginBottom: 8,
    color: "#fff",
  },
  taskItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 10,
    marginBottom: 8,
    backgroundColor: "#fafafa",
  },
  taskText: {
    flex: 1,
    fontSize: 16,
    color: "#333",
  },
  emptyText: {
    color: "#ddd",
    marginTop: 8,
    fontStyle: "italic",
    textAlign: "center",
  },
});

export default styles;
